server {
    server_name wotan.okemily.com;

    root /var/www/wotan;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
}
